name = "apex"
pages_build_output_dir = "."
compatibility_date = "2026-09-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "apex_db"
database_name = "apex-db"
database_id = "1b144350-08a0-40cb-b4a5-1356ca53fadb"

[vars]
ENVIRONMENT = "production"
PUBLIC_BASE_URL = "https://apex-8rg.pages.dev"
